### ISSUE TITLE
Can pData for C_Encrypt/C_Decrypt be NULL_PTR

### ISSUE THREAD

**Issue by computerquip-work** [oasis-tcs/pkcs11#3]
When calling C_Encrypt, it seems vague whether or not pData is allowed to be NULL_PTR or not.

For example:
```
CK_ULONG encryptedSize = 0;
C_EncryptInit(session, &someMechanism, someKey);
C_Encrypt(session, NULL_PTR, 16, NULL_PTR, &encryptedSize);
C_EncryptInit(session, NULL_PTR, 0);
```
SoftHSM, at least, appears to return CKR_ARGUMENTS_BAD for that call to C_Encrypt(). However, it seems like there's nothing that dictates pData can't be NULL_PTR. Is it expected that implementations handle that or is it left up to the implementation?

**Comment by computerquip-work** [comment]
I've gotten the impression I'm not getting an answer here. I'm just going to close this...

**Comment by inorton** [comment]
@computerquip-work  according to the 2.40 spec, C_Encrypt with a null buffer should return you the required output length:

http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959738

> **5.2 Conventions for functions returning output in a variable-length buffer**
> A number of the functions defined in Cryptoki return output produced by some cryptographic mechanism.  The amount of output returned by these functions is returned in a variable-length application-supplied buffer.  An example of a function of this sort is C_Encrypt, which takes some plaintext as an argument, and outputs a buffer full of ciphertext.
> 
> These functions have some common calling conventions, which we describe here.  Two of the arguments to the function are a pointer to the output buffer (say pBuf) and a pointer to a location which will hold the length of the output produced (say pulBufLen).  There are two ways for an application to call such a function:
> 
> 1.     If pBuf is NULL_PTR, then all that the function does is return (in *pulBufLen) a number of bytes which would suffice to hold the cryptographic output produced from the input to the function.  This number may somewhat exceed the precise number of bytes needed, but should not exceed it by a large amount.  CKR_OK is returned by the function.
> 
> 2.     If pBuf is not NULL_PTR, then *pulBufLen MUST contain the size in bytes of the buffer pointed to by pBuf.  If that buffer is large enough to hold the cryptographic output produced from the input to the function, then that cryptographic output is placed there, and CKR_OK is returned by the function.  If the buffer is not large enough, then CKR_BUFFER_TOO_SMALL is returned.  In either case, *pulBufLen is set to hold the exact number of bytes needed to hold the cryptographic output produced from the input to the function.

It sounds to me like SoftHSM is wrong here. But I could be wrong.
